### List of datasets
# RNAseq table extract
RNAseq = data.frame(data.table::fread("https://sebastian-gregoricchio.github.io/Rseb/inst/extdata/RNAseq_data.tsv", stringsAsFactors = F))

# Example of matrix generated by DeepTools
deeptools.matrix = readRDS(url("https://sebastian-gregoricchio.github.io/Rseb/inst/extdata/matrix.deepTools.rds"))

# Generate a random CNV.data table
generate.CNV = function(values, ncol, nrow, random.value, n.random) {
  data = matrix(nrow = nrow, ncol = ncol+1)

  for (i in 1:nrow) {
    set.seed(stats::runif(1,1,1000))
    data[i,] = c(paste("gene", LETTERS[i], sep="_"), sample(x = values , size = ncol, replace = T))
  }

  data = as.data.frame(data)
  colnames(data) = c("geneName", paste("patient", 1:ncol, sep="_"))

  for (i in 1:n.random) {
    set.seed(stats::runif(1,1,1000))
    data[stats::runif(1, 1, nrow), stats::runif(1, 2, ncol(data))] = random.value
  }
  return(data)
}

CNV.data = generate.CNV(values = c("gain", "gain", "gain", "loss", "loss", "loss", NA, NA), ncol = 8, nrow = 25, random.value = "gain/loss", n.random = 10)



################################################################################
# Generate data files
usethis::use_data(RNAseq, deeptools.matrix, CNV.data,
                  overwrite = T)
