#' @title RNA-seq example
#' @description Dummy example of a DESeq2 result for differential expression analysis on RNA-seq data
#' @format A data frame with 300 rows and 7 variables:
#' \describe{
#'   \item{\code{geneName}}{genes symbols}
#'   \item{\code{baseMean}}{The average of the normalized count values, dividing by size factors, taken over all samples}
#'   \item{\code{log2FC}}{the log2 value of the Fold Change expression between two conditions}
#'   \item{\code{lfcSE}}{log2 Fold Change standard error (SE)}
#'   \item{\code{stat}}{Wald statistic}
#'   \item{\code{pvalue}}{Wald test p-value}
#'   \item{\code{padj}}{BH adjusted p-values}
#'}
#' @source Simulated data
"RNAseq"
#'
#'
#'
#'
#' @title deepTools matrix example
#' @description List result of the function \link{read.computeMatrix.file} used to read a matrix.gz file generated by deepTools computeMatrix function.
#' @format A named list of 3 variables:
#' \describe{
#'   \item{\code{metadata}}{data.frame with the information gotten from the matrix_file.gz}
#'   \item{\code{matrix.data}}{data.frame with the scores gotten from}
#'   \item{\code{original.file.path}}{with full path to the original matrix_file.gz}
#'}
#' @source Simulated data
"deeptools.matrix"
#'
#'
#'
#'
#' @title CNV data results example
#' @description Simulation of Copy Number Variation (CNV) analysis on a cohort of patients.
#' @format A data frame with 25 rows and 9 variables:
#' \describe{
#'   \item{\code{geneName}}{hypothetical gene symbols}
#'   \item{\code{patient_1 ... patient_N}}{hypothetical patients ID}
#'}
#' @source Simulated data
"CNV.data"
#'
#'
#'
#'
#' @title qPCR RNA expression results example
#' @description Simulation of appliedBiosystem qPCR results
#' @format A data frame with 117 rows and 35 variables. Three of these columns are required to run \link{qPCR.rna.exp}:
#' \describe{
#'   \item{\code{Sample Name}}{Name of the samples/conditions}
#'   \item{\code{Target Name}}{The target genes to quantify}
#'   \item{\code{CT}}{Values of the cycle detected at a given threshold}
#'}
#' @source Simulated data
"qPCR.results"
